### ISSUE TITLE
PromptDialog.Choice with hero cards throw exception

### ISSUE THREAD

**Issue by Jabol92** [ObjectivityLtd/Bot.Tests.Stories#1]
If you try to use "PromptDialog.Choice" with hero cards inside the dialogue, you will get information that step #0 is not handled, however, under the hood, there is an exception "Unable to cast object of type 'Microsoft.Bot.Connector.HeroCard' to type 'Newtonsoft.Json.Linq.JObject'.".

Contact: pjablonski@objectivity.co.uk

**Comment by jkolonko** [comment]
Hi, @Jabol92 I believe this is not related to Bot.Tests.Stories but to some particular implementation. Did you mean Bot.Tests.Stories.Xunit or Bot.Tests.Stories.DirectLine? I just added support support for prompts in Bot.Tests.Stories.Xunit, does it solve your problem?

**Comment by Jabol92** [comment]
Yes, thank you very much.
